name: Helm Bump Example Workflow
on:
  push:
    branches:
      - 'v1'

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Bump the helm chart version
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump chart version
        uses: KBelbina/helm-bump-chart-version@v1
        with:
          input_file: example-helm-chart.yml
